### PR TITLE
Made visualizer work with CREATE TABLE.

### PR DESCRIPTION
**Pull request by rahularya50**

### CODE REVIEW

**Comment by kavigupta** [comment]
doesn't work? 
image

**Comment by rahularya50** [comment]
Not that sort of CREATE TABLE, since there's really nothing to visualize there.

Try `CREATE TABLE xyz AS SELECT * FROM a WHERE a = 5` or something.

**Comment by kavigupta** [comment]
why is there an erro tho?

**Comment by kavigupta** [comment]
image

still errors (different error)

**Comment by rahularya50** [comment]
It's just logging the error in the console, but it's being caught.

The error is expected.

**Comment by rahularya50** [comment]
> image
> 
> still errors (different error)

Not sure about this, will take a look

**Comment by rahularya50** [comment]
So that seems to be a bug where sql.js doesn't return anything (not even an empty table) when you try to SELECT from an empty table.

If you do `SELECT * FROM xyz` afterwards, another error appears in the console.

**Review by kavigupta — APPROVED** [review]
ok lg fix the empty table issue elsewhere

**Pull request merged**
